version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data
  backend:
    image: wuldpwnz/kittygram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media
  frontend:
    env_file: .env
    image: wuldpwnz/kittygram_frontend
  gateway:
    image: wuldpwnz/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media